# Generated by Django 5.1.5 on 2025-03-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOfDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='directors/')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('uploaded_to', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='employees/')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='management_team/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('type_is', models.CharField(max_length=100)),
                ('displacement_capacity', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('starting_system', models.CharField(max_length=100)),
                ('fuel_tank_capacity', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('fuel_consumption', models.CharField(max_length=100)),
                ('gear_box', models.CharField(max_length=100)),
                ('handle_bar', models.CharField(max_length=100)),
                ('headlight', models.CharField(max_length=100)),
                ('tyre', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('gross_weight', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='ass.productservice')),
            ],
        ),
    ]
