# Generated by Django 5.1.5 on 2025-03-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductService',
            new_name='MiniTiller',
        ),
    ]
