# Generated by Django 5.1.5 on 2025-05-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestingMachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='harvesting_machine_parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='ass.harvestingmachine')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationMachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='irrigation_machine_parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='ass.irrigationmachine')),
            ],
        ),
        migrations.CreateModel(
            name='MillingMachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='milling_machine_parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='ass.millingmachine')),
            ],
        ),
        migrations.CreateModel(
            name='MiniTillerPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mini_tiller_parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='ass.minitiller')),
            ],
        ),
        migrations.CreateModel(
            name='OtherMachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='other_machine_parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='ass.othermachine')),
            ],
        ),
        migrations.CreateModel(
            name='PlantingSowingMachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='planting_sowing_machine_parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='ass.plantingsowingmachine')),
            ],
        ),
        migrations.CreateModel(
            name='ThreshingMachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='threshing_machine_parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='ass.threshingmachine')),
            ],
        ),
        migrations.CreateModel(
            name='WeedingMachinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weeding_machine_parts/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_images', to='ass.weedingmachine')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductParts',
        ),
    ]
