# Generated by Django 5.1.5 on 2025-03-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass', '0002_rename_productservice_minitiller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardofdirector',
            name='bio',
            field=models.CharField(max_length=150),
        ),
    ]
