# Generated by Django 5.1.5 on 2025-05-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass', '0002_harvestingmachinepart_irrigationmachinepart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestingmachinepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='harvesting_machine_parts/'),
        ),
        migrations.AlterField(
            model_name='irrigationmachinepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='irrigation_machine_parts/'),
        ),
        migrations.AlterField(
            model_name='millingmachinepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='milling_machine_parts/'),
        ),
        migrations.AlterField(
            model_name='minitillerpart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mini_tiller_parts/'),
        ),
        migrations.AlterField(
            model_name='othermachinepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='other_machine_parts/'),
        ),
        migrations.AlterField(
            model_name='plantingsowingmachinepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planting_sowing_machine_parts/'),
        ),
        migrations.AlterField(
            model_name='threshingmachinepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='threshing_machine_parts/'),
        ),
        migrations.AlterField(
            model_name='weedingmachinepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weeding_machine_parts/'),
        ),
    ]
