# Generated by Django 5.1.5 on 2025-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass', '0003_alter_boardofdirector_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementteam',
            name='bio',
            field=models.CharField(max_length=150),
        ),
    ]
